
[Config.main]
port = 1234
host = "0.0.0.0"
allowed_hosts = ["first.example.com", "second.example.com"]
new_user_space_available = 10_000_000_000 # in bytes
user_image_max_size = 2_000_000 # in bytes
session_ttl = 43200 # 12h # in sec
refresh_ttl = 2592000 # 1 month # in sec

[Config.fs]
default_user_image_path = "/some/abs/path/@file" # abs pathes!!!
file_storage_path = "/some/abs/path/@storage" # abs pathes!!!
cache_dir_path = "/some/abs/path/@cache" # abs pathes!!!

[Config.databases]
mongo_db_uri = "mongodb://localhost:27017"
redis_cred = "redis://localhost:6379"
